import Head from 'next/head';
import Button from './modules/Button';

export default function Home() {
  return (
    <>
      <Head>
        <title>Login with Linkedin Trying with SSR App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Hey my first next app</div>

      <Button />
    </>
  );
}
